version: '3'

services:
  one:
    image: 'multicast-discovery/one-service:latest'
    ports:
      - '8081:8080'
    environment:
      - PROFILE=dev
  two:
    image: 'multicast-discovery/two-service:latest'
    ports:
      - '8082:8080'
    environment:
      - PROFILE=dev
