version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  gateway:
    image: 'nummi/gateway-service:latest'
    ports:
      - '8080:8080'
    depends_on:
      - kafka
    environment:
      - KAFKA_PORT=9092
  authentication:
    image: 'nummi/authentication-service:latest'
    ports:
      - '8081:8080'
    depends_on:
      - kafka
      - auth-db
    links:
      - auth-db
    environment:
      - KAFKA_PORT=9092
      - AUTH_DB_PORT=3306
      - PROFILE=dev
  search:
    image: 'nummi/search-service:latest'
    ports:
      - '8082:8080'
  mission:
    image: 'nummi/mission-service:latest'
    ports:
      - '8083:8080'
    depends_on:
      - mission-db
    links:
      - mission-db
    environment:
      - MISSION_DB_PORT=3307
      - PROFILE=dev
  auth-db:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "auth"
      MYSQL_USER: "root"
    ports:
      - 3306:3306
    volumes:
      - auth_data:/var/lib/mysql
  mission-db:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "missions"
      MYSQL_USER: "root"
    ports:
      - 3307:3306
    volumes:
      - mission_data:/var/lib/mysql

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  auth_data:
    driver: local
  mission_data:
    driver: local
