spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://10.100.132.124:3306/auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      enabled: true
