spring:
  application:
    name: one-service
#  datasource:
#    url: jdbc:mysql://nummi-db:3306/nummi?useUnicode=true&characterEncoding=utf-8
#    username: "root"
#    password: "root"
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true